language: erlang

env:
  - LUA=""
  - LUA="luajit"

branches:
  only:
    - master

install:
  - sudo apt-get install build-essential
  - sudo apt-get install luajit
  - sudo apt-get install luarocks
  - sudo luarocks install luafilesystem
  - sudo luarocks install busted

script: "make test"

notifications:
  recipients:
    - iamdeanobarnett@gmail.com.com
  email:
    on_success: change
    on_failure: always
